Code for CrackMapExec Snap package
Porchetta-Industries/CrackMapExec pull request #706
Opened 2022-12-25 17:42 UTC by GenialHacker

Copied code from https://github.com/JitPatro/enum4linux-snap/blob/main/snap/snapcraft.yaml for submitting to Upstream Repo.

2023-02-28 20:14 UTC, mpgn requested changes

2023-02-28 20:14 UTC, mpgn commented on snap/snapcraft.yaml
> +issues: https://github.com/JitPatro/crackmapexec/issues
Can you put the cme repo ?

2023-03-01 07:48 UTC, GenialHacker commented on snap/snapcraft.yaml
> +issues: https://github.com/JitPatro/crackmapexec/issues
Changed it.

2023-03-23 10:49 UTC, Xhoenix commented
@mpgn, I changed my username from GenialHacker to Xhoenix

2023-04-05 14:34 UTC, Xhoenix commented
Hey @mpgn, how about I add a desktop menu icon to the snap? If you want this, then you can provide me a png file for the desktop menu icon.

2023-09-21 10:34 UTC, closed without merging